#!/bin/bash
#
#  Output a version file that we can include at the bottom of the page
 
branch=$(git branch | sed  -n s/^\*\ //p)
version=$(git describe --tags)
cd "$(git rev-parse --show-cdup)"
if [ "$branch" == "old" ]; then
    git clean -f -x
    java -jar /home/alan/dev/yuicompressor-2.4.2.jar mbchat.js -o mbchat-min-$version.js
    java -jar /home/alan/dev/yuicompressor-2.4.2.jar mbclite.js -o mbclite-min-$version.js
    echo "<?php echo '$version';?>" > version.php
    rsync -axq --delete --exclude=supporting --exclude=pipes/ --exclude=/.git/ ./ mb:public_html/chat/
elif [ "$branch" == "old-test" ]; then
    git clean -f -x
    echo "<?php echo '$version';?>" > version.php
    rsync -axq --delete --exclude=pipes/ --exclude=/.git/ ./ /home/alan/dev/mb.com/chat/
elif [ "$branch" == "mb-com" ]; then
    git clean -f -x
    ./supporting/install/install 'http://mb.chandlerfamily.org.uk/chatserve/'
    echo "<?php echo '$version';?>" > inc/version.inc
    rsync -axq --delete remote/ mb:public_html/chat2/
    rsync -axq --delete inc/ nb:public_html/chat2/inc/
    rsync -axq --delete --exclude=/remote/ --exclude=/supporting/ --exclude=/test/  --exclude=/data/ --exclude=/.git/ ./ www-data@piglet:mb.com/chatserve/
    rsync data/private.inc www-data@piglet:mb.com/chatserve/data/
elif [ "$branch" == "mb-test" ]; then
    git clean -f -x
    ./supporting/install/install 'http://mb.home/chatserve/'
    echo "<?php echo '$version';?>" > inc/version.inc
    rsync -axq --delete remote/ /home/alan/dev/mb.com/chat2/
    rsync -axq --delete inc/ /home/alan/dev/mb.com/chat2/inc/
    rsync -axq --delete --exclude=/remote/ --exclude=/supporting/ --exclude=/test/  --exclude=/data/ --exclude=/.git/  ./ /home/alan/dev/mb.com/chatserve/
    rsync data/private.inc /home/alan/dev/mb.com/chatserve/data/
    elif [ "$branch" == "demo" ]; then
    git clean -f -x
    ./supporting/install/install 'http://www.hartley-consultants.com/chat/'
    echo "<?php echo '$version';?>" > inc/version.inc
    rsync -axq --delete  --exclude=/supporting/ --exclude=/test/  --exclude=/data/  --exclude=/remote/ --exclude=/.git/ ./ www-data@piglet:chandlerfamily.org.uk/chat/
    rsync data/private.inc www-data@piglet:chandlerfamily.org.uk/chat/data/
else
    git clean -f -X
    ./supporting/install/install 'http://chat/'
    echo "<?php echo '$version';?>" > inc/version.inc
fi

