#!/bin/bash
#
#  Output a version file that we can include at the bottom of the page
branch=$(git branch | sed  -n s/^\*\ //p)
version=$(git describe --tags)
cd "$(git rev-parse --show-cdup)"
if [ "$branch" == "old" ]; then
    git clean -f -x
    java -jar /home/alan/dev/yuicompressor-2.4.2.jar mbchat.js -o mbchat-min-$version.js
    java -jar /home/alan/dev/yuicompressor-2.4.2.jar mbclite.js -o mbclite-min-$version.js
    echo "<?php echo '$version';?>" > version.php
    rsync -axq --delete --exclude=supporting --exclude=pipes/ --exclude=/.git/ ./ mb:public_html/chat/
elif [ "$branch" == "old-test" ]; then
    git clean -f -x
    echo "<?php echo '$version';?>" > version.php
    rsync -axq --delete --exclude=pipes/ --exclude=/.git/ ./ /home/alan/dev/mb.com/chat/
elif [ "$branch" == "mb-com" ]; then
    git clean -f -x
    ./supporting/install/install 
    echo "<?php echo '$version';?>" > inc/version.inc
    rsync -aqz --delete remote/ mb:public_html/chat2/
    rsync -aqz inc/public.inc mb:public_html/chat2/
    rsync -aqz --delete --exclude=/remote/ --exclude=/supporting/ --exclude=/test/  --exclude=/data/ --exclude=/server/ --exclude=/.git/ ./ hweb:mb.com/
    rsync -aqz data/database.sql hweb:/var/chat/mb.com/
    rsqnc -aqz data/private.inc hweb:/var/chat/mb.com/
    rsync -aqz server/chatter.php hweb:/var/chat/server/
elif [ "$branch" == "mb-test" ]; then
    git clean -f -x
    ./supporting/install/install 
    echo "<?php echo '$version';?>" > inc/version.inc
    rsync -axq --delete remote/ /home/alan/dev/mb.com/chat2/
    rsync -axq inc/public.inc /home/alan/dev/mb.com/chat2/
    rsync -aqz --delete --exclude=/remote/ --exclude=/supporting/ --exclude=/test/  --exclude=/.git/ ./ /home/alan/dev/mb.com/chatserve/
    elif [ "$branch" == "demo" ]; then
    git clean -f -x
    ./supporting/install/install 
    echo "<?php echo '$version';?>" > inc/version.inc
    rsync -aq --delete --exclude=/remote/ --exclude=/supporting/ --exclude=/test/  --exclude=/data/ --exclude=/server/ --exclude=/.git/ ./ hweb:chat/
    rsync -aqz data/database.sql hweb:/var/chat/demo/
    rsqnc -aqz data/private.inc hweb:/var/chat/demo/
    rsync -aqz server/chatter.php hweb:/var/chat/server/
else
    git clean -f -X
    if [ ! -e data/users.db ] ; then sqlite3 -init supporting/users.sql data/users.db ; fi
    ./supporting/install/install 
    echo "<?php echo '$version';?>" > inc/version.inc
fi

